### ISSUE TITLE
FEATURE REQUEST: Logging to MySQL

### ISSUE THREAD

**Issue by tspicer** [Castaglia/proftpd-mod_md5#2]
In addition to creating an MD5 file, logging the checksum via a SQLNamed query would provide a clean transnational log of the transfer and resulting MD5 value. With the value in a database it can more easily be used for downstream traces/audits as it would reflect the "truth" with successful STOR operation.

**Comment by Castaglia** [comment]
Hmm.  I'm thinking that a feature of this sort could be addressed/implemented using `mod_digest`, rather than `mod_md5`.  But it would require changes to `mod_digest`, such that `mod_digest` would calculate the checksum (using which algorithm?) on uploaded files (but *not* resumed uploads or appends!); the calculated checksum would then be available for logging (_e.g._ via some `SQLLog` directive).

**Comment by tspicer** [comment]
I thought mod_digest was based on certain special ftp commands? Meaning, if those commands are not used then no checksum is generated. I don't know the details so I could be reading things wrong.

In terms of checksum, I was defaulting to md5. The reason being is that AWS uses it so if it was good enough for them no need to use anything else : )

However, you know the underlying code and mechanics better than I. If mod_digest is the right place to focus then I defer.

**Comment by tspicer** [comment]
I thought mod_digest was based on certain special ftp commands? Meaning, if those commands are not used then no checksum is generated. I don't know the details so I could be reading things wrong.

In terms of checksum, I was defaulting to md5. The reason being is that AWS uses it so if it was good enough for them no need to use anything else : )

However, you know the underlying code and mechanics better than I. If mod_digest is the right place to focus then I defer.

**Comment by tspicer** [comment]
Sorry for the closing and dupes, was having some issues doing this via my phone

**Comment by Castaglia** [comment]
I've now opened [this PR](https://github.com/proftpd/proftpd/pull/363) to make `mod_digest` do what you'd want; the PR includes an update to the `mod_digest` docs showing how to do it (and with the caveats listed).

**Comment by tspicer** [comment]
I wanted to confirm that in a test transfer via sftp and ftp I was able to get the correct sha1 checksum and algo type of be logged mysql. Thank you. Look forward to MD5 support. I can then run cross checks against S3 checksums then.

**Comment by Castaglia** [comment]
...and done; see [this PR](https://github.com/proftpd/proftpd/pull/365), which adds a `DigestDefaultAlgorithm` directive, so that you can specify MD5 as the digest algorithm.
